angular.module('sync')
    .controller('FilesController', function ($scope) {
        $scope.files = [
            {
                "id": 1,
                "name": "logo6.JPG",
                "type": "JPG",
                "group_id": null,
                "user_id": 2,
                "folder_id": 2,
                "dropbox_name": "phpG67640XKpDugtNGsT.JPG",
                "file_size": 25445,
                "mime": "image/jpeg",
                "created_at": "2016-08-20 21:07:01",
                "updated_at": "2016-08-20 21:07:01",
                "deleted_at": null,
                "groups": [],
                "user": {
                    "id": 2,
                    "email": "beastar457@gmail.com",
                    "username": "beastar457",
                    "first_name": null,
                    "avatar": "/img/you.png",
                    "provider": "streamupbox.com",
                    "provider_id": null,
                    "online": 0,
                    "last_name": null,
                    "gender": null,
                    "phone": "+250722267513",
                    "country_id": 1,
                    "verified": 1,
                    "dropbox_token": null,
                    "deleted_at": null,
                    "created_at": "2016-08-20 21:06:21",
                    "updated_at": "2016-08-21 15:10:01",
                    "stripe_active": 0,
                    "stripe_id": null,
                    "stripe_subscription": null,
                    "stripe_plan": null,
                    "trial_ends_at": null,
                    "subscription_ends_at": null
                }
            },
            {
                "id": 3,
                "name": "Get Started with Dropbox.pdf",
                "type": "pdf",
                "group_id": null,
                "user_id": 2,
                "folder_id": 2,
                "dropbox_name": "phpjd0oDw2JvXnhesCQq.pdf",
                "file_size": 692088,
                "mime": "application/pdf",
                "created_at": "2016-08-22 11:02:19",
                "updated_at": "2016-08-22 11:02:19",
                "deleted_at": null,
                "groups": [],
                "user": {
                    "id": 2,
                    "email": "beastar457@gmail.com",
                    "username": "beastar457",
                    "first_name": null,
                    "avatar": "/img/you.png",
                    "provider": "streamupbox.com",
                    "provider_id": null,
                    "online": 0,
                    "last_name": null,
                    "gender": null,
                    "phone": "+250722267513",
                    "country_id": 1,
                    "verified": 1,
                    "dropbox_token": null,
                    "deleted_at": null,
                    "created_at": "2016-08-20 21:06:21",
                    "updated_at": "2016-08-21 15:10:01",
                    "stripe_active": 0,
                    "stripe_id": null,
                    "stripe_subscription": null,
                    "stripe_plan": null,
                    "trial_ends_at": null,
                    "subscription_ends_at": null
                }
            }
        ];
    });